apiVersion: v1
kind: Service
metadata:
  name: studio
  labels:
    app: studio
  namespace: cass-operator
spec:
  type: NodePort
  selector:
    app: studio
  ports:
  - name: studio-ui
    port: 9091
    targetPort: 9091
  - name: studio-whatever
    port: 61620
    targetPort: 61620
